server:
  port: 8080
spring:      
  application:
    name: gateway-server
  cloud:
    # gateway:
    #   globalcors:
    #     corsConfigurations:
    #       '[/**]':
    #         allowedOrigins: "http://localhost"
    #         allowedMethods:
    #         - POST
    config:
      uri:
      - http://localhost:8888