server:
  port: 9000
spring:      
  application:
    name: gateway-server
  cloud:
    # gateway:
    #   globalcors:
    #     corsConfigurations:
    #       '[/**]':
    #         allowedOrigins: "*"
    #         allowedMethods:
    #         - POST
    #         - GET
    #         - PUT
    #         - DELETE
    config:
      uri:
      - http://localhost:8888