server:
  port: 9000
spring:      
  application:
    name: gateway-server
  cloud:
    # gateway:
    #   globalcors:
    #     corsConfigurations:
    #       '[/**]':
    #         allowedOrigins: "*"
    #         allowedMethods:
    #         - POST
    #         - GET
    #         - PUT
    #         - DELETE
    #   default-filters:
    #   - TokenRelay=
    config:
      uri:
      - http://localhost:8888
  security:
    oauth2:
      client:
        registration:
          custom-client:
            provider: custom-provider
            client-id: tugascloud
            client-secret: tugascloud
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/login
            client-authentication-method: basic
        provider:
          custom-provider:
            token-uri: http://localhost:9001/oauth/token
            authorization-uri: http://localhost:9001/oauth/authorize
            user-info-uri: http://localhost:9001/info/me