server:
  port: 8080
spring:      
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - POST
              - GET
              - DELETE
    config:
      uri:
      - http://localhost:8888